<a href="https://colab.research.google.com/github/kszymon/convnet/blob/main/basics%20/02_activation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$

In [2]:
def max_relu(x):
    return max(x, 0.0)

In [3]:
for i in [-10., -5., 0., 5., 10. ]:
  print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[np.float64(-2.2555630934394184),
 np.float64(-2.205338311028343),
 np.float64(-1.802994164673024),
 np.float64(-1.6457821284360132),
 np.float64(-1.5209264067912263),
 np.float64(-1.3799263296990016),
 np.float64(-1.3323464747085099),
 np.float64(-1.331145224438188),
 np.float64(-0.9747457578432303),
 np.float64(-0.9677746896938312),
 np.float64(-0.9109135830675334),
 np.float64(-0.8438609465269898),
 np.float64(-0.8062487633787947),
 np.float64(-0.7829903871199068),
 np.float64(-0.6246330027671521),
 np.float64(-0.6224149604190674),
 np.float64(-0.5713317335422342),
 np.float64(-0.5426939051410342),
 np.float64(-0.5097786716060208),
 np.float64(-0.30418960869903255),
 np.float64(-0.2977722010642292),
 np.float64(-0.2794530076995727),
 np.float64(-0.22536767688892648),
 np.float64(-0.14188435605585542),
 np.float64(-0.06026154147966233),
 np.float64(0.008535139017581258),
 np.float64(0.081184700396389),
 np.float64(0.17785271700211638),
 np.float64(0.1884108786517663),
 np.float64(0.2

In [5]:
# wygenerowanie dancych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.008535, 0.081185, 0.177853, 0.188411, 0.260626,
       0.287299, 0.370268, 0.383967, 0.427977, 0.488359, 0.52133 ,
       0.536558, 0.589156, 0.714601, 0.833964, 0.846869, 0.978018,
       1.049972, 1.080409, 1.16418 , 1.318644, 1.350592, 1.391784,
       1.492214, 1.627469])

In [6]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.255563            0.0
1 -2.205338            0.0
2 -1.802994            0.0
3 -1.645782            0.0
4 -1.520926            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLu Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [8]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [9]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
  print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [10]:
data = 3*np.random.randn(50)
data = sorted(data)
data

[np.float64(-7.074512955324008),
 np.float64(-6.804157893031402),
 np.float64(-5.651992163787055),
 np.float64(-5.277381005615563),
 np.float64(-5.234929791036664),
 np.float64(-4.702915031380623),
 np.float64(-3.897265810040582),
 np.float64(-3.5364637938233496),
 np.float64(-3.3776082857632135),
 np.float64(-3.3598538070261634),
 np.float64(-3.0544654905418698),
 np.float64(-2.929686079568946),
 np.float64(-2.827150118617161),
 np.float64(-2.790420403692449),
 np.float64(-2.3515286492862737),
 np.float64(-2.2798174754070173),
 np.float64(-1.8506430380232426),
 np.float64(-1.5271873811876207),
 np.float64(-1.0470493688428073),
 np.float64(-1.0393022909065113),
 np.float64(-0.9195104924645494),
 np.float64(-0.865985803285385),
 np.float64(-0.606995602853525),
 np.float64(-0.313911951113105),
 np.float64(-0.24469652069019918),
 np.float64(-0.19538812965848495),
 np.float64(-0.18910343215880124),
 np.float64(-0.12891664122465138),
 np.float64(-0.0746069513281918),
 np.float64(0.023666305

In [11]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[np.float64(0.0008456888953216686),
 np.float64(0.001107924944936006),
 np.float64(0.003498235667488884),
 np.float64(0.005079848703491302),
 np.float64(0.005298969823742528),
 np.float64(0.008987298650973457),
 np.float64(0.019893546482305863),
 np.float64(0.028292342953988463),
 np.float64(0.03300263748926025),
 np.float64(0.03357396644568356),
 np.float64(0.04502507655857466),
 np.float64(0.05070543316937235),
 np.float64(0.05587454638318334),
 np.float64(0.05784403981172071),
 np.float64(0.08694434393007339),
 np.float64(0.09280831962135803),
 np.float64(0.1357974146571468),
 np.float64(0.17840557825483946),
 np.float64(0.25979210539890873),
 np.float64(0.261284639788989),
 np.float64(0.28505764533169775),
 np.float64(0.2960902587810932),
 np.float64(0.35274484576130183),
 np.float64(0.4221601643020521),
 np.float64(0.4391292936568597),
 np.float64(0.4513077774162396),
 np.float64(0.4528645224621256),
 np.float64(0.46781540168068186),
 np.float64(0.4813569089592297),
 np.float64(0.

In [12]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -7.074513      0.000846
1 -6.804158      0.001108
2 -5.651992      0.003498
3 -5.277381      0.005080
4 -5.234930      0.005299

In [13]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [14]:
def tanh(x):
  return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [15]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[np.float64(-4.734267145653709),
 np.float64(-4.685343261742967),
 np.float64(-3.915752453052606),
 np.float64(-3.387793845711032),
 np.float64(-3.035324589157039),
 np.float64(-2.9084108617227593),
 np.float64(-2.772613190442246),
 np.float64(-2.681839721155338),
 np.float64(-2.5037496188406396),
 np.float64(-2.4875818864146138),
 np.float64(-2.4663992398349635),
 np.float64(-2.4533560306403146),
 np.float64(-2.141545005602852),
 np.float64(-1.9743638483794148),
 np.float64(-1.72561253306308),
 np.float64(-1.5923833896763013),
 np.float64(-1.5917693153073083),
 np.float64(-1.5302565212733814),
 np.float64(-1.5210439468532517),
 np.float64(-1.5077722749553617),
 np.float64(-1.3972673350055962),
 np.float64(-1.349242192363751),
 np.float64(-1.2521790627529665),
 np.float64(-1.2451536035409019),
 np.float64(-1.1364386489378167),
 np.float64(-1.1100290317480594),
 np.float64(-1.0575424373559512),
 np.float64(-1.02100067857237),
 np.float64(-0.9781255664126717),
 np.float64(-0.816983875922

In [16]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[np.float64(-0.9998455228474206),
 np.float64(-0.999829644737863),
 np.float64(-0.9992062600539983),
 np.float64(-0.9977200030178742),
 np.float64(-0.995391297928339),
 np.float64(-0.9940635690256724),
 np.float64(-0.9922182781697081),
 np.float64(-0.9906763861081633),
 np.float64(-0.9867136408887814),
 np.float64(-0.9862799941892584),
 np.float64(-0.985690501995424),
 np.float64(-0.9853150838946652),
 np.float64(-0.9727757846754492),
 np.float64(-0.9621708852715336),
 np.float64(-0.9385353074770969),
 np.float64(-0.9205139654504857),
 np.float64(-0.9204201715110094),
 np.float64(-0.9104684813808769),
 np.float64(-0.9088794130674492),
 np.float64(-0.9065429157130509),
 np.float64(-0.8847595449012221),
 np.float64(-0.8738743033868628),
 np.float64(-0.8488935531802333),
 np.float64(-0.846919038989944),
 np.float64(-0.8132113979165505),
 np.float64(-0.8040726534142114),
 np.float64(-0.7847214527042948),
 np.float64(-0.7702738039213427),
 np.float64(-0.7522533319934579),
 np.float64(-0.673

In [17]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.734267  -0.999846
1 -4.685343  -0.999830
2 -3.915752  -0.999206
3 -3.387794  -0.997720
4 -3.035325  -0.995391

In [18]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [19]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [20]:
data = np.random.randn(4, 5)
data

array([[-0.841928, -1.455026,  1.313361,  2.038175, -0.134185],
       [ 0.387755,  0.380896,  1.16899 ,  0.386142, -0.05891 ],
       [-1.229376, -0.503413, -0.493322,  0.202118,  0.959075],
       [ 1.551334,  0.459161, -2.853295,  1.772945,  0.295988]])

In [21]:
result = softmax(data)
result

array([[0.033314, 0.018045, 0.287511, 0.593523, 0.067607],
       [0.171955, 0.170779, 0.375578, 0.171678, 0.11001 ],
       [0.054762, 0.113178, 0.114326, 0.229177, 0.488556],
       [0.347129, 0.116457, 0.004242, 0.433247, 0.098924]])

In [22]:
result.sum(axis=1)

array([1., 1., 1., 1.])